### ISSUE TITLE
[FR / BUG] Installation

### ISSUE THREAD

**Issue by danielstankw** [gretelai/gretel-synthetics#170]
Was the installation .sh script tested? 
I have spent 3 days trying to set environment for this library to work. 
Its a nightmare. The tensorflow 2.11 is not compatible with tensorflow-estimator. 
I managed to run a part of notebook with tf==2.8 but even then it breaks.

**Comment by mckornfield** [comment]
Are you referring to https://github.com/gretelai/gretel-synthetics/blob/master/setup-utils/setup-gretel-synthetics-tensorflow28-with-gpu.sh ?

This script was tested but it hasn't been updated since last year. What is the error message you're seeing with tensorflow-estimator? And are you installing `tensorflow_estimator==2.11` or a different version?

Also you might consider reaching out on our discord if you're stuck for more than a day...
